kind: Service
apiVersion: v1
metadata:
  name: barista
  namespace: systemtest
spec:
  selector:
    app: barista
  ports:
    - port: 9080
      targetPort: 8080
  type: NodePort
---

kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: barista
  namespace: systemtest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: barista
    spec:
      containers:
      - name: barista
        image: rodolpheche/wiremock:2.6.0
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: barista
  namespace: systemtest
spec:
  rules:
    - host: barista.test.kubernetes.local
      http:
        paths:
        - path: /
          backend:
            serviceName: barista
            servicePort: 9080
---
