kind: Service
apiVersion: v1
metadata:
  name: coffee-shop-db
spec:
  selector:
    app: coffee-shop-db
  ports:
  - port: 5432
  type: NodePort
---

kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: coffee-shop-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: coffee-shop-db
    spec:
      containers:
      - name: coffee-shop-db
        image: postgres:9.5
        imagePullPolicy: Always
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
      restartPolicy: Always
---