kind: Service
apiVersion: v1
metadata:
  name: barista
spec:
  selector:
    app: barista
  ports:
    - port: 9080
  type: NodePort
---

kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: barista
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: barista
    spec:
      containers:
      - name: barista
        image: sdaschner/barista:testing-1
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /barista/resources/health
            port: 9080
      restartPolicy: Always
---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: barista
spec:
  rules:
    - host: barista.kubernetes.local
      http:
        paths:
        - path: /
          backend:
            serviceName: barista
            servicePort: 9080
---
